"""DQN (Deep Q-Network) agent.

Core idea: a small neural net Q(state) -> [value of straight, right, left]
learns to predict how good each action is. We train it with the Bellman
equation: Q(s,a) should equal reward + gamma * max(Q(next_state)).

Three RL tricks used here, all standard and all needed for stability:
  - Replay buffer: store past (state, action, reward, next_state, done)
    transitions and train on random batches, instead of only the most
    recent step. Breaks correlation between consecutive frames.
  - Epsilon-greedy exploration: early on, take random actions often (to
    discover the game); decay that over time toward trusting the network.
  - Target network: a frozen, periodically-synced copy of the model used
    only to compute training targets. Without it, the network is chasing
    a target that shifts every single update (since it's generated by the
    same weights being trained), which is a known source of instability
    in vanilla DQN. The target network only updates every N games
    (update_target(), called from train.py), so targets stay stable for
    a while between syncs.
"""
import random
from collections import deque

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

from env import STATE_SIZE, ACTION_SIZE

MAX_MEMORY = 100_000
BATCH_SIZE = 1000
LR = 0.001
GAMMA = 0.9  # discount factor for future rewards


class QNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, output_size),
        )

    def forward(self, x):
        return self.net(x)


class Agent:
    def __init__(self):
        self.n_games = 0
        self.epsilon = 0  # exploration rate, set per-game in get_action
        self.memory = deque(maxlen=MAX_MEMORY)
        self.model = QNet(STATE_SIZE, 256, ACTION_SIZE)
        self.target_model = QNet(STATE_SIZE, 256, ACTION_SIZE)
        self.target_model.load_state_dict(self.model.state_dict())
        self.target_model.eval()
        self.optimizer = optim.Adam(self.model.parameters(), lr=LR)
        self.criterion = nn.MSELoss()

    def update_target(self):
        self.target_model.load_state_dict(self.model.state_dict())

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def train_long_memory(self):
        if len(self.memory) > BATCH_SIZE:
            batch = random.sample(self.memory, BATCH_SIZE)
        else:
            batch = list(self.memory)
        states, actions, rewards, next_states, dones = zip(*batch)
        self._train_step(states, actions, rewards, next_states, dones)

    def train_short_memory(self, state, action, reward, next_state, done):
        self._train_step([state], [action], [reward], [next_state], [done])

    def _train_step(self, states, actions, rewards, next_states, dones):
        states = torch.tensor(np.array(states), dtype=torch.float32)
        next_states = torch.tensor(np.array(next_states), dtype=torch.float32)
        actions = torch.tensor(np.array(actions), dtype=torch.long)
        rewards = torch.tensor(np.array(rewards), dtype=torch.float32)

        pred = self.model(states)
        target = pred.clone()

        with torch.no_grad():
            next_q = self.target_model(next_states)

        for i in range(len(dones)):
            q_new = rewards[i]
            if not dones[i]:
                q_new = rewards[i] + GAMMA * torch.max(next_q[i])
            target[i][actions[i]] = q_new

        self.optimizer.zero_grad()
        loss = self.criterion(pred, target)
        loss.backward()
        self.optimizer.step()

    def get_action(self, state):
        # exploration decays as we play more games; after ~80 games we
        # almost always trust the network
        self.epsilon = max(0, 80 - self.n_games)
        if random.randint(0, 200) < self.epsilon:
            action = random.randint(0, ACTION_SIZE - 1)
        else:
            state_t = torch.tensor(state, dtype=torch.float32)
            prediction = self.model(state_t)
            action = torch.argmax(prediction).item()
        return action